name: MoTi
favicon: null
layout_spectrum: 0.6065902849659324
typography_spectrum: 0.13236620859242976
title: '#MoTi'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6872297504451126
  lightness: 0.7055770684964955
  saturation: 0.006556059001013637
  rhythmicContrast: 0.8121743674855679
purpose: []
