name: MoTi
favicon: null
layout_spectrum: 0.92475
typography_spectrum: 1
title: '#MoTi'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#6c7c8c'
    - '#cbcfda'
    - '#999a4a'
    - '#36363e'
  brandStrength: 0.6875
  lightness: 0.7055770684964955
  saturation: 0.006556059001013637
  rhythmicContrast: 0.8121743674855679
purpose: []
